# This file was generated by GoReleaser. DO NOT EDIT.
class Govaultenv < Formula
  desc ""
  homepage ""
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jamhed/govaultenv/releases/download/v1.0.0/govaultenv_1.0.0_darwin_amd64.tar.gz"
    sha256 "77f8706a75da01d42d37c98365fbd8561d355f15577ce4fda53da80d036c356d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jamhed/govaultenv/releases/download/v1.0.0/govaultenv_1.0.0_linux_amd64.tar.gz"
      sha256 "7c09d7c3e6778138edc61c8454399e829c6e4d2a637c31df1c15e61d0752605d"
    end
  end

  def install
    bin.install "govaultenv"
  end
end
